apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  containers:
  - image: busybox
    name: busy
    resources: {}
    command: ["sh","-c","while true; do echo 'CKad' >> /data/msg.txt; sleep 5; done"]
    volumeMounts:
    - name: mydata
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: mydata
    emptyDir: {}
status: {}
