apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx2
  name: nginx2
spec:
  initContainers:
  - image: busybox
    name: busy
    volumeMounts:
    - name: empty-vol
      mountPath: /work-dir
    command:
    - sh
    - -c
    - "wget -O /work-dir/index.html http://neverssl.com/online"
  volumes:
  - name: empty-vol
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx2
    volumeMounts:
    - name: empty-vol
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
