apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-23T08:02:26Z"
  labels:
    run: non-root-pod
  name: non-root-pod
  namespace: default
  resourceVersion: "2033"
  uid: 136055c2-2d5b-4a6c-9c8a-f24c0babab55
spec:
  containers:
  - image: redis:alpine
    imagePullPolicy: IfNotPresent
    name: non-root-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4wv2j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: k
    operator: Equal
    value: v
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-4wv2j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-23T08:02:27Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-02-23T08:02:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-23T08:02:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-23T08:02:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-23T08:02:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://41440928b30f7379b7ac608c66d8b44f6105aa6c793d20fdc0141c90c7337c6c
    image: docker.io/library/redis:alpine
    imageID: docker.io/library/redis@sha256:1b503bb77079ba644371969e06e1a6a1670bb34c2251107c0fc3a21ef9fdaeca
    lastState: {}
    name: non-root-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-23T08:02:27Z"
  hostIP: 192.13.231.9
  hostIPs:
  - ip: 192.13.231.9
  phase: Running
  podIP: 10.42.0.15
  podIPs:
  - ip: 10.42.0.15
  qosClass: BestEffort
  startTime: "2024-02-23T08:02:26Z"
