apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: myjob
spec:
  backoffLimit: 6
  completions: 2
  parallelism: 1
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: myjob
        resources: {}
        command: ["sh","-c","echo 'CKAD' && sleep 10"]
      restartPolicy: Never
status: {}
